<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>true</IsPackable>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <!-- The URL of your public GitHub repository -->
    <RepositoryUrl>https://github.com/ydahan56/YouTubeSharp</RepositoryUrl>
  
    <!-- Specify the version control system -->
    <RepositoryType>GitHub</RepositoryType>
  
    <!-- Optional: Links the package to a specific commit during packing -->
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <Version>1.0.5</Version>
    <AssemblyVersion>1.0.4</AssemblyVersion>
    <FileVersion>1.0.4</FileVersion>
    <Description>A friendly unofficial C# SDK for YouTube v3 API made for simplicity</Description>
    <PackageIcon>logo.png</PackageIcon>
    <PackageId>yoni56.YouTubeSharpSdk</PackageId>
    <Title>A friendly unofficial C# SDK for YouTube v3 API made for simplicity</Title>
    <Authors>Jonathan D.</Authors>
    <Company>NA</Company>
    <Product />
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>google, youtube, api</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Search\**" />
    <EmbeddedResource Remove="Search\**" />
    <None Remove="Search\**" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.YouTube.v3" Version="1.73.0.4053" />
    <PackageReference Include="Nito.AsyncEx.Context" Version="5.1.2" />
    <PackageReference Include="RestSharp" Version="114.0.0" />
    <PackageReference Include="SimpleInjector" Version="5.5.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="credentials.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="logo.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
