<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>true</IsPackable>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <!-- The URL of your public GitHub repository -->
    <RepositoryUrl>https://github.com/ydahan56/YouTubeSharp</RepositoryUrl>
  
    <!-- Specify the version control system -->
    <RepositoryType>GitHub</RepositoryType>
  
    <!-- Optional: Links the package to a specific commit during packing -->
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <Version>1.0.4</Version>
    <AssemblyVersion>1.0.4</AssemblyVersion>
    <FileVersion>1.0.4</FileVersion>
    <Description>A simple wrapper around the YouTube API made for simplicity.</Description>
    <PackageIcon>icon.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <!-- Include the icon in the NuGet package -->
    <None Include="icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.YouTube.v3" Version="1.73.0.4053" />
    <PackageReference Include="Nito.AsyncEx.Context" Version="5.1.2" />
    <PackageReference Include="RestSharp" Version="114.0.0" />
    <PackageReference Include="SimpleInjector" Version="5.5.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Search\Models\Request\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="credentials.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="logo.png" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
